import wrds_jkp
from aux_functions import *
wrds_session = wrds_jkp.Connection(wrds_username= "ffrdll", wrds_password="cyqrys-tamgan-0pyMbi")
end_date = pl.datetime(2023, 12, 31)
setup_folder_structure()
download_raw_data_tables(wrds_session)
gen_raw_data_dfs(wrds_session)
prepare_comp_sf('both')
prepare_crsp_sf('m')
prepare_crsp_sf('d')
combine_crsp_comp_sf()
crsp_industry()
comp_industry()
merge_industry_to_world_msf()
ff_ind_class('__msf_world2.ft', 49)
nyse_size_cutoffs('__msf_world3.ft')
classify_stocks_size_groups()
return_cutoffs('m', 0)
return_cutoffs('d', 0)
market_returns('world_dsf.ft', 'd', 1, 'return_cutoffs_daily.ft')
market_returns('world_msf.ft', 'm', 1, 'return_cutoffs.ft')
standardized_accounting_data('world',1, 'world_msf.ft',1, pl.datetime(1949, 12, 31))
create_acc_chars('acc_std_ann.ft', 'achars_world.ft', 4, 18, acc_chars_list(), 'world_msf.ft', '')
create_acc_chars('acc_std_qtr.ft', 'qchars_world.ft', 4, 18, acc_chars_list(), 'world_msf.ft', '_qitem')
combine_ann_qtr_chars('achars_world.ft', 'qchars_world.ft', acc_chars_list(), '_qitem')
market_chars_monthly('world_msf.ft', 'market_returns.ft', 0)
create_world_data_prelim('world_msf.ft', 'market_chars_m.ft', 'acc_chars_world.ft', 'world_data_prelim.ft')
ap_factors('ap_factors_daily.ft','d', 'world_dsf.ft', 'world_data_prelim.ft', 'market_returns_daily.ft', 10, 3)
ap_factors('ap_factors_monthly.ft','m', 'world_msf.ft', 'world_data_prelim.ft', 'market_returns.ft', 10, 3)
firm_age('world_msf.ft')
mispricing_factors('world_data_prelim.ft', 10, min_fcts = 3)
market_beta('beta_60m.ft','world_msf.ft','ap_factors_monthly.ft',60,36)
residual_momentum('resmom_ff3', 'world_msf.ft', 'ap_factors_monthly.ft', 36, 24, 12, 1)
residual_momentum('resmom_ff3', 'world_msf.ft', 'ap_factors_monthly.ft', 36, 24, 6, 1)
bidask_hl('corwin_schultz.ft', 'world_dsf.ft', 'market_returns_daily.ft', 10)
prepare_daily('world_dsf.ft', 'ap_factors_daily.ft')
os.system('./call_roll_apply_daily.sh')
merge_roll_apply_daily_results()
finish_daily_chars('market_chars_d.ft')
merge_world_data_prelim()
quality_minus_junk('world_data_-1.ft',10)
merge_qmj_to_world_data()
save_main_data(end_date)
save_daily_ret()
save_monthly_ret()
save_full_files_and_cleanup()
